// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeritasAtlas.Infrastructure.Persistence;

#nullable disable

namespace VeritasAtlas.Infrastructure.Migrations
{
    [DbContext(typeof(VeritasAtlasDbContext))]
    partial class VeritasAtlasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InputHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OutputHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentName");

                    b.HasIndex("CaseId");

                    b.HasIndex("Status");

                    b.ToTable("agent_runs", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Alias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId", "Value")
                        .IsUnique();

                    b.ToTable("aliases", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("SubjectPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubjectPersonId");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMaterial")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("PersonId");

                    b.HasIndex("StatementId");

                    b.HasIndex("Topic");

                    b.ToTable("claims", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.ConfidenceScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("score_value");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("CaseId");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("confidence_scores", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Contradiction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfidenceScoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeftClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<Guid>("RightClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ConfidenceScoreId");

                    b.HasIndex("RightClaimId");

                    b.HasIndex("Type");

                    b.HasIndex("LeftClaimId", "RightClaimId")
                        .IsUnique();

                    b.ToTable("contradictions", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("PublishedAtUtc");

                    b.HasIndex("SourceId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Span")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("span");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SourceId");

                    b.ToTable("evidences", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BornAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nationality")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Publication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RetractedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("publications", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("CaseId");

                    b.HasIndex("Reviewer");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TrustTier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Statement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Polarity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Predicate")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("StatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Topic")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("PersonId");

                    b.HasIndex("Topic");

                    b.ToTable("statements", (string)null);
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.AgentRun", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.Case", "Case")
                        .WithMany("AgentRuns")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Alias", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.Person", "Person")
                        .WithMany("Aliases")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Case", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.Person", "SubjectPerson")
                        .WithMany("Cases")
                        .HasForeignKey("SubjectPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SubjectPerson");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Claim", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.Case", "Case")
                        .WithMany("Claims")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeritasAtlas.Domain.Entities.Person", "Person")
                        .WithMany("Claims")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeritasAtlas.Domain.Entities.Statement", "Statement")
                        .WithMany("Claims")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Person");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.ConfidenceScore", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.AgentRun", "AgentRun")
                        .WithMany("ConfidenceScores")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeritasAtlas.Domain.Entities.Case", "Case")
                        .WithMany("ConfidenceScores")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AgentRun");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Contradiction", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.Case", "Case")
                        .WithMany("Contradictions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeritasAtlas.Domain.Entities.ConfidenceScore", "ConfidenceScore")
                        .WithMany("Contradictions")
                        .HasForeignKey("ConfidenceScoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeritasAtlas.Domain.Entities.Claim", "LeftClaim")
                        .WithMany("ContradictionsAsLeft")
                        .HasForeignKey("LeftClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeritasAtlas.Domain.Entities.Claim", "RightClaim")
                        .WithMany("ContradictionsAsRight")
                        .HasForeignKey("RightClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("ConfidenceScore");

                    b.Navigation("LeftClaim");

                    b.Navigation("RightClaim");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Document", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.Source", "Source")
                        .WithMany("Documents")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Evidence", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.Document", "Document")
                        .WithMany("Evidences")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeritasAtlas.Domain.Entities.Source", "Source")
                        .WithMany("Evidences")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Person", b =>
                {
                    b.OwnsOne("VeritasAtlas.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("display_name");

                            b1.Property<string>("FamilyName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("family_name");

                            b1.Property<string>("GivenName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("given_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("middle_name");

                            b1.HasKey("PersonId");

                            b1.ToTable("persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Publication", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.Case", "Case")
                        .WithMany("Publications")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeritasAtlas.Domain.Entities.Review", "Review")
                        .WithMany("Publications")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Review", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.AgentRun", "AgentRun")
                        .WithMany("Reviews")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeritasAtlas.Domain.Entities.Case", "Case")
                        .WithMany("Reviews")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentRun");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Source", b =>
                {
                    b.OwnsOne("VeritasAtlas.Domain.ValueObjects.SourceReference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("SourceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Domain")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("reference_domain");

                            b1.Property<string>("ExternalId")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("reference_external_id");

                            b1.Property<string>("LanguageCode")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("reference_language_code");

                            b1.Property<string>("Url")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("reference_url");

                            b1.HasKey("SourceId");

                            b1.ToTable("sources");

                            b1.WithOwner()
                                .HasForeignKey("SourceId");
                        });

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Statement", b =>
                {
                    b.HasOne("VeritasAtlas.Domain.Entities.Document", "Document")
                        .WithMany("Statements")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeritasAtlas.Domain.Entities.Evidence", "Evidence")
                        .WithMany("Statements")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeritasAtlas.Domain.Entities.Person", "Person")
                        .WithMany("Statements")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("VeritasAtlas.Domain.ValueObjects.StatementText", "Text", b1 =>
                        {
                            b1.Property<Guid>("StatementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("text_normalized");

                            b1.Property<string>("Raw")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("text_raw");

                            b1.HasKey("StatementId");

                            b1.ToTable("statements");

                            b1.WithOwner()
                                .HasForeignKey("StatementId");
                        });

                    b.Navigation("Document");

                    b.Navigation("Evidence");

                    b.Navigation("Person");

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.AgentRun", b =>
                {
                    b.Navigation("ConfidenceScores");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Case", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("Claims");

                    b.Navigation("ConfidenceScores");

                    b.Navigation("Contradictions");

                    b.Navigation("Publications");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Claim", b =>
                {
                    b.Navigation("ContradictionsAsLeft");

                    b.Navigation("ContradictionsAsRight");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.ConfidenceScore", b =>
                {
                    b.Navigation("Contradictions");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Document", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("Statements");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Evidence", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Person", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Cases");

                    b.Navigation("Claims");

                    b.Navigation("Statements");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Review", b =>
                {
                    b.Navigation("Publications");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Source", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("VeritasAtlas.Domain.Entities.Statement", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
