language: en-US

reviews:
  profile: assertive
  request_changes_workflow: false
  auto_review:
    enabled: false
    auto_incremental_review: false
    drafts: false
    base_branches:
      - main
