param(
    [string]$BaseUrl = "https://localhost:7091",
    [int]$TimeoutSeconds = 60
)

$ErrorActionPreference = "Stop"

function Invoke-JsonPost {
    param(
        [string]$Uri,
        [object]$Body
    )

    $json = $Body | ConvertTo-Json -Depth 10
    return Invoke-RestMethod -Method Post -Uri $Uri -ContentType "application/json" -Body $json
}

function Wait-ForApi {
    param(
        [string]$BaseUrl,
        [int]$TimeoutSeconds
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)

    while ((Get-Date) -lt $deadline) {
        try {
            Invoke-WebRequest -Uri "$BaseUrl/health" -UseBasicParsing -TimeoutSec 5 | Out-Null
            Write-Host "API is reachable at $BaseUrl" -ForegroundColor Green
            return
        }
        catch {
            Start-Sleep -Seconds 2
        }
    }

    throw "API did not start within $TimeoutSeconds seconds."
}

Write-Host ""
Write-Host "Running reusable smoke test pack..." -ForegroundColor Cyan

Wait-ForApi -BaseUrl $BaseUrl -TimeoutSeconds $TimeoutSeconds

$health = Invoke-RestMethod -Method Get -Uri "$BaseUrl/health"
$dbHealth = Invoke-RestMethod -Method Get -Uri "$BaseUrl/health/db"

Write-Host "Health endpoint responded." -ForegroundColor Green
Write-Host "DB health endpoint responded." -ForegroundColor Green

$person = Invoke-JsonPost `
    -Uri "$BaseUrl/api/v1/persons" `
    -Body @{
        displayName = "Reusable Smoke User"
        createdBy   = "phase3.4-smoke-pack"
    }

$alias = Invoke-JsonPost `
    -Uri "$BaseUrl/api/v1/persons/$($person.id)/aliases" `
    -Body @{
        alias     = "RSU"
        createdBy = "phase3.4-smoke-pack"
    }

$case = Invoke-JsonPost `
    -Uri "$BaseUrl/api/v1/cases" `
    -Body @{
        title           = "Reusable smoke test case"
        summary         = "Generated by reusable smoke script"
        subjectPersonId = $person.id
        createdBy       = "phase3.4-smoke-pack"
    }

$agentRun = Invoke-JsonPost `
    -Uri "$BaseUrl/api/v1/agent-runs/start" `
    -Body @{
        agentName    = "ReusableSmokeAgent"
        agentType    = "Ingestion"
        caseId       = $case.id
        inputPayload = "{ `"caseId`": `"$($case.id)`" }"
        createdBy    = "phase3.4-smoke-pack"
    }

Invoke-RestMethod `
    -Method Post `
    -Uri "$BaseUrl/api/v1/agent-runs/$($agentRun.id)/complete" `
    -ContentType "application/json" `
    -Body (@{
        outputPayload = "{ `"result`": `"ok`" }"
        errorMessage  = $null
        notes         = "Completed by reusable smoke pack"
        updatedBy     = "phase3.4-smoke-pack"
    } | ConvertTo-Json -Depth 10) | Out-Null

$review = Invoke-JsonPost `
    -Uri "$BaseUrl/api/v1/reviews" `
    -Body @{
        caseId      = $case.id
        submittedBy = "phase3.4-smoke-pack"
        notes       = "Reusable smoke review"
    }

$completedReview = Invoke-JsonPost `
    -Uri "$BaseUrl/api/v1/reviews/$($review.id)/complete" `
    -Body @{
        decision = "Approved"
        reviewer = "phase3.4-smoke-pack"
        notes    = "Approved by reusable smoke pack"
    }

Invoke-RestMethod `
    -Method Post `
    -Uri "$BaseUrl/api/v1/cases/$($case.id)/approve" `
    -ContentType "application/json" `
    -Body (@{
        approvedBy = "phase3.4-smoke-pack"
        notes      = "Approved by reusable smoke pack"
    } | ConvertTo-Json -Depth 10) | Out-Null

$persons = Invoke-RestMethod -Method Get -Uri "$BaseUrl/api/v1/persons?page=1&pageSize=10"
$cases = Invoke-RestMethod -Method Get -Uri "$BaseUrl/api/v1/cases?page=1&pageSize=10"
$agentRuns = Invoke-RestMethod -Method Get -Uri "$BaseUrl/api/v1/agent-runs?page=1&pageSize=10"
$reviews = Invoke-RestMethod -Method Get -Uri "$BaseUrl/api/v1/reviews?page=1&pageSize=10"

Write-Host ""
Write-Host "Reusable smoke test results" -ForegroundColor Cyan
Write-Host "---------------------------"
Write-Host "Person Id:       $($person.id)"
Write-Host "Alias Id:        $($alias.id)"
Write-Host "Case Id:         $($case.id)"
Write-Host "Agent Run Id:    $($agentRun.id)"
Write-Host "Review Id:       $($review.id)"
Write-Host "Persons count:   $($persons.totalCount)"
Write-Host "Cases count:     $($cases.totalCount)"
Write-Host "AgentRuns count: $($agentRuns.totalCount)"
Write-Host "Reviews count:   $($reviews.totalCount)"
Write-Host ""
Write-Host "SMOKE PACK PASSED." -ForegroundColor Green
